### ISSUE TITLE
pretrain model

### ISSUE THREAD

**Issue by TyrionChou** [amzn/convolutional-handwriting-gan#1]
Thank you for your work. could you publish a pretrain model？

**Comment by rlit** [comment]
We are working on it, hope it will be approved soon

**Comment by rlit** [comment]
pre-trained models will be added [here](https://github.com/amzn/convolutional-handwriting-gan/releases/tag/CVPR20)

**Comment by TyrionChou** [comment]
> pre-trained models will be added [here](https://github.com/amzn/convolutional-handwriting-gan/releases/tag/CVPR20)

thank you very much！
