### ISSUE TITLE
How can I change the style of writer

### ISSUE THREAD

**Issue by archwolf118** [amzn/convolutional-handwriting-gan#2]
Thanks, this project is wonderful and useful for the handwriting generating. I have generated some sample from your code, but I want to change different style. What should I do?
Thanks you!

**Comment by sharonFogel** [comment]
You can change the noise vector to change the style. The style changes randomly with each noise vector you choose so you can't generate the style of a specific writer. However, if you generate a few words with the same input noise vector, their style will be identical.

**Comment by archwolf118** [comment]
@sharonFogel thank you for your reply.
